// Generated by CoffeeScript 1.3.3
(function() {
  var dinkumise, falafel;

  falafel = require('falafel');

  dinkumise = function(src) {
    return falafel(src, function(node) {
      if (node.value === true) {
        return node.update('!!"fair dinkum"');
      }
    });
  };

  module.exports = dinkumise;

}).call(this);
